#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libyami
Version  : 1.3.1
Release  : 12
URL      : https://github.com/intel/libyami/archive/1.3.1.tar.gz
Source0  : https://github.com/intel/libyami/archive/1.3.1.tar.gz
Summary  : Intel open source media infrastructure base on libva.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: libyami-lib = %{version}-%{release}
Requires: libyami-license = %{version}-%{release}
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libva-wayland)

%description
Yet Another Media Infrastructure.
It is YUMMY to your video experience on Linux like platform.
Yami is core building block for media solution. it parses video stream
and decodes them leverage hardware acceleration.

%package dev
Summary: dev components for the libyami package.
Group: Development
Requires: libyami-lib = %{version}-%{release}
Provides: libyami-devel = %{version}-%{release}
Requires: libyami = %{version}-%{release}

%description dev
dev components for the libyami package.


%package lib
Summary: lib components for the libyami package.
Group: Libraries
Requires: libyami-license = %{version}-%{release}

%description lib
lib components for the libyami package.


%package license
Summary: license components for the libyami package.
Group: Default

%description license
license components for the libyami package.


%prep
%setup -q -n libyami-1.3.1
cd %{_builddir}/libyami-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604353653
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static --enable-vp9dec \
--enable-vp9enc \
--enable-h265enc \
--enable-h265dec \
--enable-jpegenc \
--enable-vp8enc \
--enable-dmabuf
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604353653
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libyami
cp %{_builddir}/libyami-1.3.1/LICENSE.md %{buildroot}/usr/share/package-licenses/libyami/2b8b815229aa8a61e483fb4ba0588b8b6c491890
cp %{_builddir}/libyami-1.3.1/codecparsers/dboolhuff.LICENSE %{buildroot}/usr/share/package-licenses/libyami/4dbe7c1f3a1833a88333a7c282119323e9ef44fa
cp %{_builddir}/libyami-1.3.1/codecparsers/vp9quant.LICENSE %{buildroot}/usr/share/package-licenses/libyami/e9e216e41252f23ea09d1377ed8b9061db7db903
cp %{_builddir}/libyami-1.3.1/gtestsrc/gtest/LICENSE %{buildroot}/usr/share/package-licenses/libyami/5a2314153eadadc69258a9429104cd11804ea304
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libyami/VideoCommonDefs.h
/usr/include/libyami/VideoDecoderCapi.h
/usr/include/libyami/VideoDecoderDefs.h
/usr/include/libyami/VideoDecoderHost.h
/usr/include/libyami/VideoDecoderInterface.h
/usr/include/libyami/VideoEncoderCapi.h
/usr/include/libyami/VideoEncoderDefs.h
/usr/include/libyami/VideoEncoderHost.h
/usr/include/libyami/VideoEncoderInterface.h
/usr/include/libyami/VideoPostProcessDefs.h
/usr/include/libyami/VideoPostProcessHost.h
/usr/include/libyami/VideoPostProcessInterface.h
/usr/include/libyami/Yami.h
/usr/include/libyami/YamiC.h
/usr/include/libyami/YamiVersion.h
/usr/lib64/libyami.so
/usr/lib64/pkgconfig/libyami.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libyami.so.1
/usr/lib64/libyami.so.1.3.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libyami/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/libyami/4dbe7c1f3a1833a88333a7c282119323e9ef44fa
/usr/share/package-licenses/libyami/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/libyami/e9e216e41252f23ea09d1377ed8b9061db7db903
