#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libyami
Version  : 1.1.0
Release  : 3
URL      : https://github.com/01org/libyami/archive/libyami-1.1.0.tar.gz
Source0  : https://github.com/01org/libyami/archive/libyami-1.1.0.tar.gz
Summary  : yami based v4l2 plugin
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: libyami-lib
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(libva-wayland)

%description
libyami
Yet Another Media Infrastructure.
It is YUMMY to your video experience on Linux like platform.

%package dev
Summary: dev components for the libyami package.
Group: Development
Requires: libyami-lib
Provides: libyami-devel

%description dev
dev components for the libyami package.


%package lib
Summary: lib components for the libyami package.
Group: Libraries

%description lib
lib components for the libyami package.


%prep
%setup -q -n libyami-libyami-1.1.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490711900
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1490711900
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libyami/VideoCommonDefs.h
/usr/include/libyami/VideoDecoderCapi.h
/usr/include/libyami/VideoDecoderDefs.h
/usr/include/libyami/VideoDecoderHost.h
/usr/include/libyami/VideoDecoderInterface.h
/usr/include/libyami/VideoEncoderCapi.h
/usr/include/libyami/VideoEncoderDefs.h
/usr/include/libyami/VideoEncoderHost.h
/usr/include/libyami/VideoEncoderInterface.h
/usr/include/libyami/VideoPostProcessDefs.h
/usr/include/libyami/VideoPostProcessHost.h
/usr/include/libyami/VideoPostProcessInterface.h
/usr/include/libyami/Yami.h
/usr/include/libyami/YamiC.h
/usr/include/libyami/YamiVersion.h
/usr/lib64/libyami.so
/usr/lib64/pkgconfig/libyami.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libyami.so.1
/usr/lib64/libyami.so.1.1.0
